#
# (c) Copyright 2019 Jeff Kight
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
# Ansible playbooks to Manage CAs, Intermediate CAs and Certificates
#
# Author: Jeff Kight <jeff@kight.net>
#
---

- hosts: localhost
  connection: local
  gather_facts: yes

  roles:
    - cert-manager

  vars_prompt:
    - name: cert_domain
      prompt: "Enter CA domain"
      private: no
      confirm: no
      default: "domain.tld"
      when: site_id is not defined

    - name: cert_org
      prompt: "Enter the certificate organization"
      private: no
      confirm: no
      default: "My Company"
      when: cert_org is not defined

    - name: cert_org_unit
      prompt: "Enter the certificate organizational unit"
      private: no
      confirm: no
      default: "Infrastructure Services"
      when: cert_org_unit is not defined

    - name: cert_country
      prompt: "Enter the certificate country"
      private: no
      confirm: no
      default: "US"
      when: cert_country is not defined

    - name: cert_state
      prompt: "Enter the certificate state"
      private: no
      confirm: no
      default: "State"
      when: cert_state is not defined

    - name: cert_locality
      prompt: "Enter the certificate locality"
      private: no
      confirm: no
      default: "City"
      when: cert_locality is not defined

    - name: cert_duration
      prompt: "Enter the certificate duration in days"
      private: no
      confirm: no
      default: 3650
      when: cert_duration is not defined

    # - name: cert_distinguished_name
    #   prompt: "Enter distinguished name"
    #   private: no
    #   confirm: no
    #   default: tester
    #   when: cert_distinguished_name is not defined

    - name: cert_server_list
      prompt: "Enter server names (FQDN list separated by commas)"
      private: no
      confirm: no
      default: vip.domain.tld,www.domain.tld
      when: cert_server_list is not defined

    - name: cert_ip_list
      prompt: "Enter IPs (list separated by commas)"
      private: no
      confirm: no
      default: 192.168.100.100
      when: cert_ip_list is not defined

    - name: cert_server
      prompt: "Server cert (true/false)"
      private: no
      confirm: no
      default: true
      when: cert_server is not defined

    - name: cert_client
      prompt: "Client cert (true/false)"
      private: no
      confirm: no
      default: false
      when: cert_client is not defined

  tasks:
    - set_fact:
        tls_dir: "{{ tls_root }}/{{ cert_domain }}"
        cert_servers_strip: "{{ cert_server_list | replace(' ', '') }}"
        cert_ips_strip: "{{ cert_ip_list | replace(' ', '') }}"

    - set_fact:
        cert_servers: "{{ cert_servers_strip.split(',') }}"
        cert_ips: "{{ cert_ips_strip.split(',') }}"

    - set_fact:
        cert_servers_ips: "{{ cert_servers | union(cert_ips) }}"
        host_dir: "{{ tls_dir }}/{{ store_dir }}/{{ cert_servers[0] }}/{{ ansible_date_time.date }}"

    - import_tasks: roles/cert-manager/tasks/prep_certs.yml
    - import_tasks: roles/cert-manager/tasks/create_cert.yml
