#
# (c) Copyright 2019 Jeff Kight
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
# Ansible playbooks to Manage CAs, Intermediate CAs and Certificates
#
# Author: Jeff Kight <jeff@kight.net>
#
---

- name: Create directory structure
  file:
    path: "{{ host_dir }}"
    state: directory
    mode: 0755

- name: Copy CSR to TLS directory
  copy:
    src: "{{ cert_csr_path }}"
    dest: "{{ host_dir }}/{{ csr_cn }}.{{ host_csr_suffix }}"
    mode: 0644
